config/routes.rb
Rails.application.routes.draw do
  root "cameras#index"
  resources :cameras, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/camera.rb
class Camera < ApplicationRecord
  has_one_attached :image

  validates :text, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cameras_controller.rb
class CamerasController < ApplicationController
  def index
    @cameras = Camera.all
  end

  def new
    @camera = Camera.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cameras_helper.rb
module CamerasHelper
end

app/views/cameras/index.html.erb
<h1>Home</h1><br>
<% @cameras.each do |camera| %>
  <div>
    <div>
      <%= camera.text %>
    </div>
    <div>
      <%= camera.image %>
    </div>
  </div>
  <br><br>
<% end %>

<br>

<%= link_to 'カメラ撮影', new_camera_path %>

app/views/cameras/new.html.erb
<h1>HTMLカメラ</h1>

<div>
  <%= form_with model: @camera, url: cameras_path, id="form", local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%= f.label :text %>: 
    <%= f.text_field :text %><br>
    <div class="camera-area">
      <video id="camera"></video>
      <canvas id="picture"></canvas>
      <div class="button">
        <button type="button" id="shutter">シャッター</button>
      </div><br>

      <audio id="se" preload="auto">
        <source src="<%= asset_path('camera_shutter_sound.mp3') %>" type="audio/mp3">
      </audio>
    </div>
    <%= f.submit "送信" %><br>
  <% end %>
</div>

<%= link_to '戻る', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CameraTraining</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>